print('Hello World!')
print('Diego Rodriguez Garnier')
print('Es programming time')
print('_______________________________________________________')
print('')
print('')
print('')
print('')
print('----Menu-----')
print('1. Hablar con un agente')
print('2. Salir del Menu principal')
print('3. Solicitar tarjeta de credito')
print('4. Solicitar cita en el BAC..')
